export {
  PiCalendarCheck as CalendarIcon,
  PiCamera as CameraIcon,
  PiCarProfile as VehicleIcon,
  PiCheckCircle as CheckIcon,
  PiClipboardText as JobCardIcon,
  PiCreditCard as PaymentIcon,
  PiGauge as OdometerIcon,
  PiPackage as PartsIcon,
  PiMagnifyingGlass as SearchIcon,
  PiReceipt as InvoiceIcon,
  PiTimer as TimerIcon,
  PiUserCircle as CustomerIcon,
  PiWarning as WarningIcon,
  PiWrench as WorkOrderIcon,
} from 'react-icons/pi';
